### ISSUE TITLE
Resilience goals for v0.9

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#111]
Despite overall progress on #78, we still have many changes to make. These will probably be rolled into v0.9 rather than v0.8. Here they are:
- [x] Use of spawning (#69)
  - Should there be a default spawn frequency for all objects created? (moved to #169)
- [x] Make game periodically run `git push` and `git pull`
  - [x] The main issue with this one is that `git push` requires a login every time when cloned over `https`. Need to figure out how to use `ssh` instead.
  - [x] We also want to allow `git pull` to change the contents of the main game files, but not allow wizards in the game to do that. Could be difficult.
- [x] Prevent wizards from editing main game files
  - [x] We were thinking about doing this through `chmod` on the server, since any python functions can be redefined.

Additionally, these features are not completely necessary, but would be nice:
- Detect and shut down memory leaks (moved to #140)
- Prevent bad wizard code from crashing or freezing the game (moved to #140)

**Comment by rivques** [comment]
Not only should we respawn objects, we should periodically close things like secret passages.

**Comment by davedotluebke** [comment]
One thing we've planned to do is to have rooms self-destruct after they've been empty long enough. This will free up some memory. As a bonus, something like a secret passage will close because the room will be reloaded. So we probably only need to explicitly close secret passages and otherwise reset things that happen in rooms that are frequently occupied (like the library). 

We do want to make sure that if a event is registered to (say) close a secret passage in a room, and that room gets destroyed (from being empty too long) before the event comes up, then the event will not cause an error trying to access a room that isn't there.

**Comment by 1Bayshore** [comment]
One important thing we still need to add is the `git push` functionality. This hasn't been implemented yet because it requires a password when cloning with https.

**Comment by 1Bayshore** [comment]
The remaining tasks have been moved to their own issues. Closing this as all tasks are completed.
