### ISSUE TITLE
Allow reconnecting to characters in game

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#124]
Currently, if the websocket goes down, there is no way to access your character. Your character simply sits there and does nothing until the game ends. Instead, if you try to log in as the same character, you wind up with a duplicate. 

The login code should be able to detect if the character you specified is already logged in, and, if so, allow you to reconnect to that character. Additionally, both the gameserver code and the webclient should be able to deal with a broken connection.

Steps:
- [ ] Detect on both ends when the websocket disconnects and respond accordingly.
- [x] The login code should detect if the character you have selected is already in the game. If so, it should offer for you to take over that character (point your input to that console).
- [ ] To allow users to voluntarily use this feature, we could add a "suspend" command that disconnected the user's character, but without saving or quitting.

While we're working on this, it might be nice to have periodic auto-saves in case the game crashes.

**Comment by davedotluebke** [comment]
Ideas: 
- [ ] Since it's difficult to tell if the client (or server) has actually disconnected or simply gone quiet, instead have the server check once a minute whether there's been any input for the last minute. If not, tell the player to do something or be logged out, and give them another minute before logging out. 
- [ ] When somebody attempts to join the game but already has a player object in the game, we currently give them the option to take over the existing player, or log in as a different character. We could also give them a "restart" option that would destroy the current object and start a new one back at their starting location. To avoid cheating (e.g. to get safely out of a fight they are going to lose by effectively teleporting home) we would want there to be a delay before they could use this option.

**Comment by 1Bayshore** [comment]
We have made some progress, but I'm not sure whether the remaining steps are necessary (or possible). Should we just close this issue?
