### ISSUE TITLE
Perceive is hard to spell and causes errors when typed by bad spellers (i.e. @rivques)

### ISSUE THREAD

**Issue by rivques** [davedotluebke/old-skool-text-game#149]
We should rename this. Alternatively, we could just add a function called `percieve` that just calls `perceive` and logs the problem.

**Comment by davedotluebke** [comment]
I wouldn't object to taking a few common methods and making super-short utility versions of them, e.g. `Player.p()` for perceive, and `Thing.e()` for emit. Feel free to do these two, and propose others. But I refuse to bake intentional misspellings into the codebase - what would I tell your parents and teachers? :-)
