### ISSUE TITLE
Strange one-off code in diagram_sentence (parse.py line 94)

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#15]
I don't understand what this code is supposed to do in parse.py, and wonder if it is a bug or a leftover from a previous version of the parser.

                if sV == 'go' and p == 'in':  # what is this doing? 
                    continue

It's around line 94 in parse.py. Owen please check it out and decide if it should in fact be deleted, or reply to this issue with an explanation of what this code is about.

**Comment by 1Bayshore** [comment]
That code is an exception to the normal parsing, where `'in'` is a direction, not a preposition, and that code makes sure the following code, which would categorize `'in'` as a preposition, ending up using sentence structure 1 (_**Verb DirectObject Preposition InderectObject**_) instead of the necessary sentence structure 2 (_**Verb DirectObject**_), not correct, and consider `'go in'` a verb and preposition, not a valid command.
