### ISSUE TITLE
Dropping a weapon should automatically unwield it

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#30]
Dropping a weapon should automatically unwield it.

**Comment by davedotluebke** [comment]
I implemented this. It was trickier than I expected to override the default 'drop' action in Thing. I had to create a new function and search for the existing action for the 'drop' verb, then replace the function associated with it. And in my new drop function, I had to call the old one and return it's value appropriately. Check out how I did this, because we will also want to do the same for unwearing armor by dropping it.
