### ISSUE TITLE
Book pagination not working

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#47]
'read the blue book' in the library dumps the entire contents of the book at once, including the #* tags that are supposed to indicated page breaks.

**Comment by dhuss83** [comment]
It's dumping the whole book because every line has 4 extra spaces in front of itself, and the #* tag cannot have whitespace before it and must be immediately followed by a newline in order to work as it's currently coded. Removing the whitespace stops it from dumping the entire contents but introduces a problem where if you try to read a second book and type "read page 2", it will display page two from the first book instead.

I wonder if a cleaner way to handle reading would be to have a separate module (parser?) take over that has commands like "[read] table of contents" (or "[read] toc"),  "previous [page]", "next [page]", "page #", "close [book]". Turning to a page could be as simple as typing the number and <enter>. "Previous" and "next" could be abbreviated as "p" and "n". Another possibility is simply hitting <enter> without typing anything could simply advance to the next page, and the book could automatically close once you've reached the end. Handling books this way might also help with Issue #49 to get the special parse commands for reading out of the main parser file.

**Comment by 1Bayshore** [comment]
I created a system for input takeover. When that is merged back in it might be possible to do this. This system does not stop the user from perceiving anything and a console "escape" command, along with other console commands, would keep the user in control. Thanks for the comment!

**Comment by dannyhuss** [comment]
That sounds great! I actually started making changes to improve book reading yesterday. Today, I added some more functionality, and it seems to be working great. I may try to implement your new takeover system into 'book.py' unless you already have plans to do that yourself. If you do, you may want to make the changes on top of what I've already done to the reading system. I fixed several bugs and made it so books could be closed. I also made it so when a book is dropped and someone else picks it up and reads it that it opens to the first page instead of the last page that the previous person read. There is also a "read previous page" command now (abbreviated: read prev). 

Also, GitHub is showing two nearly identical commits from me above this message. Disregard the first one. I'm new to GitHub and Git in general and didn't realize that what I was doing on my fork would be visible here. I went back and undid a change from the first time I made that commit. It was related to blue_book.py. My MUD client was having trouble displaying UTF-8 characters and I thought telnet just couldn't handle anything more than ASCII. As it turns out, my telnet program shows it fine, but not the MUD client. Anyway I tried to cover up the fact that I had changed it at all, thinking I could straighten it all out before I made a pull request. Apparently I was wrong.

**Comment by 1Bayshore** [comment]
@dannyhuss thanks for the help! That sounds really useful. I still need to merge the input takeover code into the master branch (pull request #52), it is in [my fork](https://github.com/1Bayshore/old-skool-text-game) right now. However, if you want to, you can merge it from there with the shell command `$ git pull https://github.com/1Bayshore/old-skool-text-game.git master`.

**Comment by dannyhuss** [comment]
@1Bayshore I've finished the modification to the book reading system. I say modification, but it was really an overhaul. Essentially everything I changed in the reading system before, I had to rewrite in some way or simply undo. Not that I'm complaining. I think the new system is a lot nicer than the previous one. Feel free to download it and let me know what you think if you find the time. You can check the commit message 3083754433456cdb2fd59116023911004521208e for a more detailed description of what I did. The branch with the changes is called '1Bayshore' since it was synced up with your master branch.

**Comment by dannyhuss** [comment]
I had an idea and added a short transcript that shows exactly what the new reading system looks like. I posted it in a comment on the pull request: https://github.com/davedotluebke/old-skool-text-game/pull/56
