### ISSUE TITLE
Add money and plurals

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#68]
# Plurals
Currently, there is no good parser support for things that are the same. For instance, if you are in a room with five oysters in it, the description is this:
```
Here you see:
a closed normal oyster
a closed normal oyster
a closed normal oyster
a closed normal oyster
a closed normal oyster
```
Instead, you should see something like this:
```
Here you see:
5 closed normal oysters
```
Additionally, the parser should support typing things like `take 5 oysters` or `take 30 gold`. `All` also needs to be implemented, so a user can type `take all gold`.

Perhaps the best way to do this would be to associate items that shared the same short descriptions. This way, we would associate objects that appeared to be the same without further examination.
# Money
Implementing money would also be very helpful to the game. Money will be used as a plural frequently.

We also need to decide on what the denominations of money are in the game. For example, should we have copper, silver, and gold coins, where 1 gold = 20 silver and 1 silver = 20 copper? (One thing we probably don't want is gold coins to be the only coins worth having, we want them to be something that is valuable.)

These two issues are closely tied together, and so we should probably open a new branch to address both of them at the same time.

**Comment by davedotluebke** [comment]
I like the idea of starting a new branch to deal with these issues. I wanted to add a note on how Genesis dealt with pluralities (I think "plurality" is the right word for this; "plural" is more about the language construct, like adding 's' to a singular). In Genesis, when you were carrying or found money, it looked like:

- "a few gold coins" 
- "a small pile of gold coins"
- "a large pile of gold coins"
- "a giant pile of gold coins" 

and so on (I don't remember all the phrases but they were like the above). You could "count" a pile to see how many were there. This seems like a good practice. If we want to get fancy we could have the system remember if you counted them, and after counting display as "a pile of 47 gold coins" until the value changes. I think we should have a small plurality (2-5?) show up as "5 oysters", and maybe 6-10 show up as "a few oysters", 10-20 as "a small pile of oysters" and so on.  

I don't recall if Genesis applied this to everything or just coins, but I like the idea that it can automatically apply to everything that is identical in some fashion - maybe same path and default short description? Doing this seems tricky. How do we make something be in a plurality? Maybe a plurality is a separate object, like a container? Or maybe it's a field in an object, so you only store one copy of an object (e.g. in the player's `contents` field), and indicate how many of that object there are? This is definitely easier if it only applies to a few special objects, like coins, that are designed to be identical to begin with. But that makes it a more interesting challenge!

**Comment by davedotluebke** [comment]
Also Genesis and other MUDs support "Take all from corpse" which is what you usually type when you kill a monster/player/etc. to get all their gear.

**Comment by 1Bayshore** [comment]
One thing we probably should consider is that we may want to make items that _seem_ to be the same appear in the same plurality. Otherwise, you could figure out pretty quickly that something that looked the same as everything else wasn't actually the same object.

Also, I already created a branch for this but have not checked anything into it. It is named `plurals_and_money`.

**Comment by davedotluebke** [comment]
Let's try this system:

## Decision 
Plurals only apply to multiple identical copies of the same object. Objects with the same short description but different attributes are not combined into a Plurality. For example, a player holding two identical copies of the 'rusty sword' object would see "Two rusty swords" in their inventory. However if one of the sword objects had been magically sharpened to have a higher damage attribute, the player would see "a rusty sword" and "a rusty sword" in their inventory, as they would if they were holding two totally different objects which both happen to have the short description "rusty sword". (Hopefully the code for magically sharpening the sword would add the adjective 'sharpened' or something to avoid this confusion.)

## Implementation
Plurals are implemented with a `Plurality` object. Pluralities keep a count of how many objects are in them; if this count drops to 1 the Plurality object is removed and replaced with the object itself. Pluralities also store references to 2 identical copies of the object: the `canonical` version and the `spare` version. The idea is that the `canonical` object determines what this is a plurality _of_, and the `spare` object is a copy which might get changed by actions the user takes. 

The parser looks for and executes actions inside the `spare` version of the the object. Then the plurality checks if the `canonical` and `spare` objects are still identical. If so, no change is made. If the action caused the `spare` object to differ from the `canonical` object, then the spare object is removed from the plurality (since it is no longer identical) and added to the location of the plurality. A new `spare` object for the plurality is then copied from the `canonical` object. 

Pluralities are created when there are at least 2 identical objects in a single `Container`. When another identical object is added to the Container, it will be added to the plurality, increasing the `count` by one. We'll need to overload the `insert` and `extract` operations in a Container.

Finally, players can type things like `take 10 gold coins` to take a certain amount of the object. A copy is made (also a plurality) and both objects' counts are set to the appropriate number.

## Example
Suppose the user is carrying 4 identical wooden torches. The game represents these with a single Plurality object which has a `canonical` field pointing to a torch object, a `spare` field pointing to another torch object, and a `count` field set to 4. If the user types `inventory` the game will list '4 wooden torches'. Suppose the torch object supports a verb "wave" which prints "You wave the torch around," but has no other effect. If the player types `wave torch` then the parser will search the user's location and contents for objects that support the "wave" verb. The actions of the plurality are set to the actions of the `spare` object, so the parser will call the Action associated with the "wave" verb in the `spare` object's `actions[]` field. The `spare` object handles the verb but remains unchanged and identical to the `canonical` object, and nothing else happens.  But suppose the user types `light torch`, and the "light" action changes the lightness attribute of the torch and changes the short description to "a lit wooden torch". Now the `spare` and `canonical` objects are no longer identical, so the `spare` object gets moved directly to the player's `contents[]` field, a new `spare` object is made by copying the `canonical` object, and the `count` field is decremented. Now if the player types `inventory` the game will list '3 wooden torches' and 'a lit wooden torch'. 

## Affected systems

1. The Parser will need to look inside each Plurality to see possible Actions that might handle the typed verb. Alternatively the Plurality `actions[]` field could be set to that of the `canonical` object. 
2. Containers will need to support creating, destroying, and adding to a Plurality when objects are inserted or extracted from the Container.
3. All code that inspects the `contents[]` field will need to deal with Plurality objects. Let's add examples here as we think of them or find them in the code:
   1. Determining whether a room is lit or dark by recursively looking for light sources in the room.
   2. Printing out inventory (perhaps the Plurality simply creates a short description based on count, e.g. "a bunch of wooden torches").
   3. Evaluating weight and volume limits when adding or subtracting things to a Container (including a player's inventory).
   4. The Parser currently handles adjectives like "first", "second", "third" so you can type things like `drop the third wooden torch`. This code will have to be adjusted to work consistently with Pluralities, for example when the items in a player's inventory are listed as "three wooden torches" and "a lit wooden torch", if the player types "drop fourth torch" they should drop the lit one.

**Comment by 1Bayshore** [comment]
# A New Proposal
After the discussion, we have now agreed on a new approach. Instead of having a plurality object, each Thing will contain a `plurality` field. It will be defaulted to `1`. When you insert an object into a container, the code will check each other object in the container to see if it is identical to the object being inserted (by comparing their __dict__ fields). If so, the code will destroy the new object and increment the `plurality` field of the plural object (already in the container) by the `plurality` field of the new object (which is 1 if the new object is a singleton and >1 if the new object is itself a plurality). This allows commands such as `put 4 gold coins in the bag` (note the parser must be extended to allow this).

Removing an object decrements the plurality count as above and creates a new copy of the object being removed using a `Thing.replicate()` function that we will define. The default behavior will be to use the `copy.copy()` function from the Python Standard Library, except the `contents` and `actions` fields. Wizards creating objects that need deep copies of a field should overload the `replicate` function.

**Comment by 1Bayshore** [comment]
One possible compromise between optimizing the speed of operations and making it simple to deal with plural oDOs and oIDOs would be to have the parser only deal with plural objs and let the action functions deal with the few cases where oDOs and oIDOs need to be split. We should at least consider this option.
