### ISSUE TITLE
Adding shops

### ISSUE THREAD

**Issue by 1Bayshore** [davedotluebke/old-skool-text-game#98]
As a continuation of #92, we want to implement shopping to the game. This will be very complicated, so we should probably go with the simplest implementation. Here's what we're currently thinking:
- [x] The `long_desc` of a shop should indicate how to list the shop's inventory.
- [x] Players will be able to look at items in the shop, but not do anything with them. (Perhaps a verb like `inspect` would be a good way to allow players to get the item's `long_desc`.)
- [x] Shopkeepers will have some dialogue, which will tell the players something about the area, perhaps informing them of a quest or such. They should also be able to help a player navigate the system for buying and selling.
- [x] Players will be able to buy items from the shop with a single command. (This avoids any complications with bargaining and the timing of pay/receive items.)
- [x] Shops should restock basic items with some frequency.
- [ ] I think it would be neat if shops saved their inventory over game restarts. This isn't extremely urgent, however.

**Comment by davedotluebke** [comment]
Here's what the `buy` command should do, in order:

1. Verify the thing you want to buy is in the shop
2. Verify that you have enough money to buy said thing
3. Take the money from the player
  a. Take smallest denominations first
  b. so sort the player's money objects by value, keeping track of pluralities
  c. take it in order of increasing value, keeping track of when you've taken enough to pay for the thing
  d. Might need to reduce the plurality for the last money we take, e.g. if player has a gold coin with 20 plurality and we need to take 8 gold coin's worth of value, we need to reduce the plurality to 12. 
    - We could actually move the money to the shopkeeper (splitting the plurality of the final gold coin object in the example above), but it seems simpler not to have the shops actually posses lots of money. 
4. Make change from the player's money and give the player back the change
5. Remove the item from the shop's inventory
6. Move the item to the player's inventory

Note that steps 4 and 6 could fail due to player not being able to carry the change and/or thing (weight and volume limits). Might test for that first, or support rolling back the transaction if the `move_to()` calls fail.

**Comment by davedotluebke** [comment]
Basic buying and selling works! Nice job @1Bayshore. Leaving this issue open but labeling "enhancement" as the remaining items are more cosmetic or "nice to have" than necessary functionality.

**Comment by 1Bayshore** [comment]
I have finished implementing all except saving inventories, which I rolled into #128. Closing this issue.
